// src/runtime/compatibility.test.js
// ==============================================================================
// AUTO-GENERATED BY tools/build_truth.js - DO NOT EDIT MANUALLY
// ==============================================================================
import { Evaluator } from './evaluator.js';
import { block } from '../parser/qbasic/controlFlow.js';
import { test, assertEqual, registerSuite } from '../test_runner.js';

function executeToEnv(sourceCode) {
    const evaluator = new Evaluator();
    const ast = block.run(sourceCode).result;
    const process = evaluator.evaluate(ast);
    let state = process.next();
    while (!state.done) state = process.next();
    return evaluator.env;
}

registerSuite('Truth Vector: STDLIB: Math & Floating-Point Unit', () => {

    test('INT Function', () => {
        const code = `
            IntPos = INT(2.8)
            IntNeg = INT(-2.2)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('IntPos'), 2, "IntPos assertion failed");
        assertEqual(env.lookup('IntNeg'), -3, "IntNeg assertion failed");
    });

    test('FIX Function', () => {
        const code = `
            FixPos = FIX(2.8)
            FixNeg = FIX(-2.8)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('FixPos'), 2, "FixPos assertion failed");
        assertEqual(env.lookup('FixNeg'), -2, "FixNeg assertion failed");
    });

    test('CINT Function', () => {
        const code = `
            CintUp = CINT(2.6)
            CintHalfEven = CINT(2.5)
            CintHalfOdd = CINT(3.5)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('CintUp'), 3, "CintUp assertion failed");
        assertEqual(env.lookup('CintHalfEven'), 2, "CintHalfEven assertion failed");
        assertEqual(env.lookup('CintHalfOdd'), 4, "CintHalfOdd assertion failed");
    });

    test('/ (Floating-Point Division)', () => {
        const code = `
            FloatDiv! = 5 / 2
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('FloatDiv!'), 2.5, "FloatDiv! assertion failed");
    });

    test('\\ (Integer Division)', () => {
        const code = `
            IntDiv! = 5 \\ 2
            IntDivRound! = 5.6 \\ 1.9
            IntDivBankerEven! = 2.5 \\ 1
            IntDivBankerOdd! = 3.5 \\ 1
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('IntDiv!'), 2, "IntDiv! assertion failed");
        assertEqual(env.lookup('IntDivRound!'), 3, "IntDivRound! assertion failed");
        assertEqual(env.lookup('IntDivBankerEven!'), 2, "IntDivBankerEven! assertion failed");
        assertEqual(env.lookup('IntDivBankerOdd!'), 4, "IntDivBankerOdd! assertion failed");
    });

    test('MOD Operator', () => {
        const code = `
            ModNorm! = 10 MOD 3
            ModNeg! = -10 MOD 3
            ModRound! = 10.6 MOD 3
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('ModNorm!'), 1, "ModNorm! assertion failed");
        assertEqual(env.lookup('ModNeg!'), -1, "ModNeg! assertion failed");
        assertEqual(env.lookup('ModRound!'), 2, "ModRound! assertion failed");
    });

    test('ABS Function', () => {
        const code = `
            AbsVal = ABS(-42)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('AbsVal'), 42, "AbsVal assertion failed");
    });

    test('SQR Function', () => {
        const code = `
            SqrVal = SQR(16)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('SqrVal'), 4, "SqrVal assertion failed");
    });

    test('SIN Function', () => {
        const code = `
            SinZero = CINT(SIN(0) * 1000)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('SinZero'), 0, "SinZero assertion failed");
    });

    test('COS Function', () => {
        const code = `
            CosZero = CINT(COS(0) * 1000)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('CosZero'), 1000, "CosZero assertion failed");
    });

    test('TAN Function', () => {
        const code = `
            TanZero = CINT(TAN(0) * 1000)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('TanZero'), 0, "TanZero assertion failed");
    });

    test('ATN Function', () => {
        const code = `
            AtnZero = CINT(ATN(0) * 1000)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('AtnZero'), 0, "AtnZero assertion failed");
    });

    test('EXP Function', () => {
        const code = `
            ExpZero = CINT(EXP(0) * 1000)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('ExpZero'), 1000, "ExpZero assertion failed");
    });

    test('LOG Function', () => {
        const code = `
            LogOne = CINT(LOG(1) * 1000)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('LogOne'), 0, "LogOne assertion failed");
    });
});

registerSuite('Truth Vector: STDLIB: Strings & Type Casting', () => {

    test('STR$ Function', () => {
        const code = `
            PosStr$ = STR$(42)
            ZeroStr$ = STR$(0)
            NegStr$ = STR$(-15)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('PosStr$'), " 42", "PosStr$ assertion failed");
        assertEqual(env.lookup('ZeroStr$'), " 0", "ZeroStr$ assertion failed");
        assertEqual(env.lookup('NegStr$'), "-15", "NegStr$ assertion failed");
    });

    test('HEX$ Function', () => {
        const code = `
            NormHex$ = HEX$(255)
            RoundDownHex$ = HEX$(12.4)
            RoundUpHex$ = HEX$(12.6)
            NegTwosComp$ = HEX$(-1)
            LargeNegTwosComp$ = HEX$(-100000)
            ZeroHex$ = HEX$(0)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('NormHex$'), "FF", "NormHex$ assertion failed");
        assertEqual(env.lookup('RoundDownHex$'), "C", "RoundDownHex$ assertion failed");
        assertEqual(env.lookup('RoundUpHex$'), "D", "RoundUpHex$ assertion failed");
        assertEqual(env.lookup('NegTwosComp$'), "FFFF", "NegTwosComp$ assertion failed");
        assertEqual(env.lookup('LargeNegTwosComp$'), "FFFE7960", "LargeNegTwosComp$ assertion failed");
        assertEqual(env.lookup('ZeroHex$'), "0", "ZeroHex$ assertion failed");
    });

    test('VAL Function', () => {
        const code = `
            NormVal! = VAL("123.45")
            HexVal = VAL("&H10")
            HexLowVal = VAL("&hc")
            OctVal = VAL("&O10")
            GarbageVal = VAL("NOTANUMBER")
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('NormVal!'), 123.45, "NormVal! assertion failed");
        assertEqual(env.lookup('HexVal'), 16, "HexVal assertion failed");
        assertEqual(env.lookup('HexLowVal'), 12, "HexLowVal assertion failed");
        assertEqual(env.lookup('OctVal'), 8, "OctVal assertion failed");
        assertEqual(env.lookup('GarbageVal'), 0, "GarbageVal assertion failed");
    });

    test('LEFT$ Function', () => {
        const code = `
            BaseStr$ = "SYSCLONE"
            NormLeft$ = LEFT$(BaseStr$, 3)
            OverLeft$ = LEFT$(BaseStr$, 50)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('NormLeft$'), "SYS", "NormLeft$ assertion failed");
        assertEqual(env.lookup('OverLeft$'), "SYSCLONE", "OverLeft$ assertion failed");
    });

    test('RIGHT$ Function', () => {
        const code = `
            BaseStr$ = "SYSCLONE"
            NormRight$ = RIGHT$(BaseStr$, 5)
            OverRight$ = RIGHT$(BaseStr$, 50)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('NormRight$'), "CLONE", "NormRight$ assertion failed");
        assertEqual(env.lookup('OverRight$'), "SYSCLONE", "OverRight$ assertion failed");
    });

    test('MID$ Function', () => {
        const code = `
            BaseStr$ = "SYSCLONE"
            NormMid$ = MID$(BaseStr$, 4, 2)
            NoLenMid$ = MID$(BaseStr$, 4)
            OutBoundsMid$ = MID$(BaseStr$, 99, 2)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('NormMid$'), "CL", "NormMid$ assertion failed");
        assertEqual(env.lookup('NoLenMid$'), "CLONE", "NoLenMid$ assertion failed");
        assertEqual(env.lookup('OutBoundsMid$'), "", "OutBoundsMid$ assertion failed");
    });

    test('SPACE$ Function', () => {
        const code = `
            SpcStr$ = SPACE$(3)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('SpcStr$'), "   ", "SpcStr$ assertion failed");
    });

    test('STRING$ Function', () => {
        const code = `
            StrChar$ = STRING$(4, "A")
            StrLong$ = STRING$(3, "XYZ")
            StrCode$ = STRING$(3, 65)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('StrChar$'), "AAAA", "StrChar$ assertion failed");
        assertEqual(env.lookup('StrLong$'), "XXX", "StrLong$ assertion failed");
        assertEqual(env.lookup('StrCode$'), "AAA", "StrCode$ assertion failed");
    });

    test('LEN Function', () => {
        const code = `
            StrLen = LEN("HELLO")
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('StrLen'), 5, "StrLen assertion failed");
    });

    test('UCASE$ Function', () => {
        const code = `
            UpStr$ = UCASE$("hello")
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('UpStr$'), "HELLO", "UpStr$ assertion failed");
    });

    test('LCASE$ Function', () => {
        const code = `
            LowStr$ = LCASE$("HELLO")
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('LowStr$'), "hello", "LowStr$ assertion failed");
    });

    test('LTRIM$ Function', () => {
        const code = `
            LTrimStr$ = LTRIM$("  TEXT")
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('LTrimStr$'), "TEXT", "LTrimStr$ assertion failed");
    });

    test('RTRIM$ Function', () => {
        const code = `
            RTrimStr$ = RTRIM$("TEXT  ")
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('RTrimStr$'), "TEXT", "RTrimStr$ assertion failed");
    });

    test('CHR$ Function', () => {
        const code = `
            Char$ = CHR$(65)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('Char$'), "A", "Char$ assertion failed");
    });

    test('ASC Function', () => {
        const code = `
            AscVal = ASC("A")
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('AscVal'), 65, "AscVal assertion failed");
    });

    test('INSTR Function', () => {
        const code = `
            FoundIdx = INSTR("HELLO WORLD", "WORLD")
            OffsetIdx = INSTR(3, "HELLO WORLD, HELLO", "HELLO")
            NotFoundIdx = INSTR("HELLO", "Z")
            OutBoundsIdx = INSTR(100, "HELLO", "L")
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('FoundIdx'), 7, "FoundIdx assertion failed");
        assertEqual(env.lookup('OffsetIdx'), 14, "OffsetIdx assertion failed");
        assertEqual(env.lookup('NotFoundIdx'), 0, "NotFoundIdx assertion failed");
        assertEqual(env.lookup('OutBoundsIdx'), 0, "OutBoundsIdx assertion failed");
    });
});

registerSuite('Truth Vector: STDLIB: Memory, Types & Structures', () => {

    test('Default Implicit Typing (SINGLE)', () => {
        const code = `
            DefaultFloat = 3.14
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('DefaultFloat'), 3.14, "DefaultFloat assertion failed");
    });

    test('DEFINT Statement', () => {
        const code = `
            DEFINT A-Z
            ImplicitIntA = 2.5
            ImplicitIntB = 2.6
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('ImplicitIntA'), 2, "ImplicitIntA assertion failed");
        assertEqual(env.lookup('ImplicitIntB'), 3, "ImplicitIntB assertion failed");
    });

    test('DEFSNG Statement', () => {
        const code = `
            DEFINT A-Z
            DEFSNG A-Z
            ImplicitSng = 5.8
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('ImplicitSng'), 5.8, "ImplicitSng assertion failed");
    });

    test('Explicit Type Suffix Override', () => {
        const code = `
            DEFINT A-Z
            OverrideFloat! = 3.14
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('OverrideFloat!'), 3.14, "OverrideFloat! assertion failed");
    });

    test('Memory Aliasing (DIM AS STRING)', () => {
        const code = `
            DIM AliasTest AS STRING
            AliasTest = "NIBBLES"
            Extracted$ = AliasTest$
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('Extracted$'), "NIBBLES", "Extracted$ assertion failed");
    });

    test('Fixed-Length String Padding', () => {
        const code = `
            DIM PadStr AS STRING * 5
            PadStr = "HI"
            PadLen = LEN(PadStr)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('PadStr'), "HI   ", "PadStr assertion failed");
        assertEqual(env.lookup('PadLen'), 5, "PadLen assertion failed");
    });

    test('Fixed-Length String Truncation', () => {
        const code = `
            DIM TruncStr AS STRING * 3
            TruncStr = "123456"
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('TruncStr'), "123", "TruncStr assertion failed");
    });

    test('SWAP Statement', () => {
        const code = `
            SwapA = 99
            SwapB = 42
            SWAP SwapA, SwapB
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('SwapA'), 42, "SwapA assertion failed");
        assertEqual(env.lookup('SwapB'), 99, "SwapB assertion failed");
    });

    test('ERASE Statement (Static Arrays)', () => {
        const code = `
            DIM EraseArr(1 TO 3)
            EraseArr(2) = 777
            ERASE EraseArr
            ClearedVal = EraseArr(2)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('ClearedVal'), 0, "ClearedVal assertion failed");
    });
});
