// src/runtime/qbasic/compatibility.test.js
// ==============================================================================
// AUTO-GENERATED BY tools/build_truth.js - DO NOT EDIT MANUALLY
// ==============================================================================
import { test, assertEqual, registerSuite } from '../../test_runner.js';
import { executeQBasic } from './qbasic_test_utils.js';

function executeToEnv(sourceCode) {
    return executeQBasic(sourceCode).env;
}

registerSuite('Truth Vector: STDLIB: Math & Floating-Point Unit', () => {

    test('INT Function', () => {
        const code = `
            IntPos = INT(2.8)
            IntNeg = INT(-2.2)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('IntPos'), 2, "IntPos assertion failed");
        assertEqual(env.lookup('IntNeg'), -3, "IntNeg assertion failed");
    });

    test('FIX Function', () => {
        const code = `
            FixPos = FIX(2.8)
            FixNeg = FIX(-2.8)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('FixPos'), 2, "FixPos assertion failed");
        assertEqual(env.lookup('FixNeg'), -2, "FixNeg assertion failed");
    });

    test('CINT Function', () => {
        const code = `
            CintUp = CINT(2.6)
            CintHalfEven = CINT(2.5)
            CintHalfOdd = CINT(3.5)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('CintUp'), 3, "CintUp assertion failed");
        assertEqual(env.lookup('CintHalfEven'), 2, "CintHalfEven assertion failed");
        assertEqual(env.lookup('CintHalfOdd'), 4, "CintHalfOdd assertion failed");
    });

    test('/ (Floating-Point Division)', () => {
        const code = `
            FloatDiv! = 5 / 2
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('FloatDiv!'), 2.5, "FloatDiv! assertion failed");
    });

    test('\\ (Integer Division)', () => {
        const code = `
            IntDiv! = 5 \\ 2
            IntDivRound! = 5.6 \\ 1.9
            IntDivBankerEven! = 2.5 \\ 1
            IntDivBankerOdd! = 3.5 \\ 1
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('IntDiv!'), 2, "IntDiv! assertion failed");
        assertEqual(env.lookup('IntDivRound!'), 3, "IntDivRound! assertion failed");
        assertEqual(env.lookup('IntDivBankerEven!'), 2, "IntDivBankerEven! assertion failed");
        assertEqual(env.lookup('IntDivBankerOdd!'), 4, "IntDivBankerOdd! assertion failed");
    });

    test('MOD Operator', () => {
        const code = `
            ModNorm! = 10 MOD 3
            ModNeg! = -10 MOD 3
            ModRound! = 10.6 MOD 3
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('ModNorm!'), 1, "ModNorm! assertion failed");
        assertEqual(env.lookup('ModNeg!'), -1, "ModNeg! assertion failed");
        assertEqual(env.lookup('ModRound!'), 2, "ModRound! assertion failed");
    });

    test('ABS Function', () => {
        const code = `
            AbsInt = ABS(-42)
            AbsFloatStr$ = LTRIM$(STR$(ABS(-3.14159)))
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('AbsInt'), 42, "AbsInt assertion failed");
        assertEqual(env.lookup('AbsFloatStr$'), "3.14159", "AbsFloatStr$ assertion failed");
    });

    test('SQR Function', () => {
        const code = `
            SqrVal = SQR(16)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('SqrVal'), 4, "SqrVal assertion failed");
    });

    test('SIN Function', () => {
        const code = `
            SinZero = CINT(SIN(0) * 1000)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('SinZero'), 0, "SinZero assertion failed");
    });

    test('COS Function', () => {
        const code = `
            CosZero = CINT(COS(0) * 1000)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('CosZero'), 1000, "CosZero assertion failed");
    });

    test('TAN Function', () => {
        const code = `
            TanZero = CINT(TAN(0) * 1000)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('TanZero'), 0, "TanZero assertion failed");
    });

    test('ATN Function', () => {
        const code = `
            AtnZero = CINT(ATN(0) * 1000)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('AtnZero'), 0, "AtnZero assertion failed");
    });

    test('EXP Function', () => {
        const code = `
            ExpZero = CINT(EXP(0) * 1000)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('ExpZero'), 1000, "ExpZero assertion failed");
    });

    test('LOG Function', () => {
        const code = `
            LogOne = CINT(LOG(1) * 1000)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('LogOne'), 0, "LogOne assertion failed");
    });
});

registerSuite('Truth Vector: STDLIB: Strings & Type Casting', () => {

    test('STR$ Function', () => {
        const code = `
            PosStr$ = STR$(42)
            ZeroStr$ = STR$(0)
            NegStr$ = STR$(-15)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('PosStr$'), " 42", "PosStr$ assertion failed");
        assertEqual(env.lookup('ZeroStr$'), " 0", "ZeroStr$ assertion failed");
        assertEqual(env.lookup('NegStr$'), "-15", "NegStr$ assertion failed");
    });

    test('HEX$ Function', () => {
        const code = `
            NormHex$ = HEX$(255)
            RoundDownHex$ = HEX$(12.4)
            RoundUpHex$ = HEX$(12.6)
            NegTwosComp$ = HEX$(-1)
            LargeNegTwosComp$ = HEX$(-100000)
            ZeroHex$ = HEX$(0)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('NormHex$'), "FF", "NormHex$ assertion failed");
        assertEqual(env.lookup('RoundDownHex$'), "C", "RoundDownHex$ assertion failed");
        assertEqual(env.lookup('RoundUpHex$'), "D", "RoundUpHex$ assertion failed");
        assertEqual(env.lookup('NegTwosComp$'), "FFFF", "NegTwosComp$ assertion failed");
        assertEqual(env.lookup('LargeNegTwosComp$'), "FFFE7960", "LargeNegTwosComp$ assertion failed");
        assertEqual(env.lookup('ZeroHex$'), "0", "ZeroHex$ assertion failed");
    });

    test('VAL Function', () => {
        const code = `
            NormVal! = VAL("123.45")
            HexVal = VAL("&H10")
            HexLowVal = VAL("&hc")
            OctVal = VAL("&O10")
            GarbageVal = VAL("NOTANUMBER")
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('NormVal!'), 123.45, "NormVal! assertion failed");
        assertEqual(env.lookup('HexVal'), 16, "HexVal assertion failed");
        assertEqual(env.lookup('HexLowVal'), 12, "HexLowVal assertion failed");
        assertEqual(env.lookup('OctVal'), 8, "OctVal assertion failed");
        assertEqual(env.lookup('GarbageVal'), 0, "GarbageVal assertion failed");
    });

    test('LEFT$ Function', () => {
        const code = `
            BaseStr$ = "SYSCLONE"
            NormLeft$ = LEFT$(BaseStr$, 3)
            OverLeft$ = LEFT$(BaseStr$, 50)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('NormLeft$'), "SYS", "NormLeft$ assertion failed");
        assertEqual(env.lookup('OverLeft$'), "SYSCLONE", "OverLeft$ assertion failed");
    });

    test('RIGHT$ Function', () => {
        const code = `
            BaseStr$ = "SYSCLONE"
            NormRight$ = RIGHT$(BaseStr$, 5)
            OverRight$ = RIGHT$(BaseStr$, 50)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('NormRight$'), "CLONE", "NormRight$ assertion failed");
        assertEqual(env.lookup('OverRight$'), "SYSCLONE", "OverRight$ assertion failed");
    });

    test('MID$ Function', () => {
        const code = `
            BaseStr$ = "SYSCLONE"
            NormMid$ = MID$(BaseStr$, 4, 2)
            NoLenMid$ = MID$(BaseStr$, 4)
            OutBoundsMid$ = MID$(BaseStr$, 99, 2)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('NormMid$'), "CL", "NormMid$ assertion failed");
        assertEqual(env.lookup('NoLenMid$'), "CLONE", "NoLenMid$ assertion failed");
        assertEqual(env.lookup('OutBoundsMid$'), "", "OutBoundsMid$ assertion failed");
    });

    test('SPACE$ Function', () => {
        const code = `
            SpcStr$ = SPACE$(3)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('SpcStr$'), "   ", "SpcStr$ assertion failed");
    });

    test('STRING$ Function', () => {
        const code = `
            StrChar$ = STRING$(4, "A")
            StrLong$ = STRING$(3, "XYZ")
            StrCode$ = STRING$(3, 65)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('StrChar$'), "AAAA", "StrChar$ assertion failed");
        assertEqual(env.lookup('StrLong$'), "XXX", "StrLong$ assertion failed");
        assertEqual(env.lookup('StrCode$'), "AAA", "StrCode$ assertion failed");
    });

    test('LEN Function', () => {
        const code = `
            StrLen = LEN("HELLO")
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('StrLen'), 5, "StrLen assertion failed");
    });

    test('UCASE$ Function', () => {
        const code = `
            UpStr$ = UCASE$("hello")
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('UpStr$'), "HELLO", "UpStr$ assertion failed");
    });

    test('LCASE$ Function', () => {
        const code = `
            LowStr$ = LCASE$("HELLO")
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('LowStr$'), "hello", "LowStr$ assertion failed");
    });

    test('LTRIM$ Function', () => {
        const code = `
            LTrimStr$ = LTRIM$("  TEXT")
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('LTrimStr$'), "TEXT", "LTrimStr$ assertion failed");
    });

    test('RTRIM$ Function', () => {
        const code = `
            RTrimStr$ = RTRIM$("TEXT  ")
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('RTrimStr$'), "TEXT", "RTrimStr$ assertion failed");
    });

    test('CHR$ Function', () => {
        const code = `
            Char$ = CHR$(65)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('Char$'), "A", "Char$ assertion failed");
    });

    test('ASC Function', () => {
        const code = `
            AscVal = ASC("A")
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('AscVal'), 65, "AscVal assertion failed");
    });

    test('INSTR Function', () => {
        const code = `
            FoundIdx = INSTR("HELLO WORLD", "WORLD")
            OffsetIdx = INSTR(3, "HELLO WORLD, HELLO", "HELLO")
            NotFoundIdx = INSTR("HELLO", "Z")
            OutBoundsIdx = INSTR(100, "HELLO", "L")
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('FoundIdx'), 7, "FoundIdx assertion failed");
        assertEqual(env.lookup('OffsetIdx'), 14, "OffsetIdx assertion failed");
        assertEqual(env.lookup('NotFoundIdx'), 0, "NotFoundIdx assertion failed");
        assertEqual(env.lookup('OutBoundsIdx'), 0, "OutBoundsIdx assertion failed");
    });

    test('MKI$ and CVI (16-bit Integer Packing)', () => {
        const code = `
            PackedStr$ = MKI$(258)
            Length = LEN(PackedStr$)
            RestoredPos = CVI(PackedStr$)
            RestoredNeg = CVI(MKI$(-1))
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('Length'), 2, "Length assertion failed");
        assertEqual(env.lookup('RestoredPos'), 258, "RestoredPos assertion failed");
        assertEqual(env.lookup('RestoredNeg'), -1, "RestoredNeg assertion failed");
    });

    test('MKS$ and CVS (32-bit Float Packing)', () => {
        const code = `
            PackedSng$ = MKS$(1.5)
            SngLength = LEN(PackedSng$)
            RestoredSng! = CVS(PackedSng$)
            RestoredZero! = CVS(MKS$(0))
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('SngLength'), 4, "SngLength assertion failed");
        assertEqual(env.lookup('RestoredSng!'), 1.5, "RestoredSng! assertion failed");
        assertEqual(env.lookup('RestoredZero!'), 0, "RestoredZero! assertion failed");
    });
});

registerSuite('Truth Vector: CORE: Control Flow & Jumps', () => {

    test('FOR...NEXT Statement', () => {
        const code = `
            ' 1. Terminal Overshoot (Positive & Negative)
            CountA = 0: FOR I = 1 TO 5: CountA = CountA + 1: NEXT
            CountB = 0: FOR J = 5 TO 1 STEP -1: CountB = CountB + 1: NEXT
            
            ' 2. Bound Immutability
            Limit = 3: Inc = 1: Runs = 0
            FOR K = 1 TO Limit STEP Inc
              Runs = Runs + 1
              Limit = 10
              Inc = 5
            NEXT
            
            ' 3. Iterator Mutation
            MutRuns = 0
            FOR M = 1 TO 5
              MutRuns = MutRuns + 1
              M = M + 1
            NEXT
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('CountA'), 5, "CountA assertion failed");
        assertEqual(env.lookup('I'), 6, "I assertion failed");
        assertEqual(env.lookup('CountB'), 5, "CountB assertion failed");
        assertEqual(env.lookup('J'), 0, "J assertion failed");
        assertEqual(env.lookup('Runs'), 3, "Runs assertion failed");
        assertEqual(env.lookup('K'), 4, "K assertion failed");
        assertEqual(env.lookup('Limit'), 10, "Limit assertion failed");
        assertEqual(env.lookup('Inc'), 5, "Inc assertion failed");
        assertEqual(env.lookup('MutRuns'), 3, "MutRuns assertion failed");
        assertEqual(env.lookup('M'), 7, "M assertion failed");
    });

    test('EXIT FOR Statement', () => {
        const code = `
            ' 1. Basic Exit and Iterator Retention
            TargetVal = 0: FinalI = 0
            FOR I = 5 TO 1 STEP -1
              IF I = 3 THEN
                TargetVal = I
                EXIT FOR
              END IF
            NEXT
            FinalI = I
            
            ' 2. Scope Isolation (Nested Loops)
            OuterCount = 0: InnerCount = 0
            FOR Outer = 1 TO 3
              OuterCount = OuterCount + 1
              FOR Inner = 1 TO 5
                IF Inner = 2 THEN EXIT FOR
                InnerCount = InnerCount + 1
              NEXT
            NEXT
            FinalOuter = Outer
            FinalInner = Inner
            
            ' 3. Short-Circuit Execution
            Flag = 0: FinalK = 0
            FOR K = 1 TO 5
              EXIT FOR
              Flag = 99
            NEXT
            FinalK = K
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('TargetVal'), 3, "TargetVal assertion failed");
        assertEqual(env.lookup('FinalI'), 3, "FinalI assertion failed");
        assertEqual(env.lookup('OuterCount'), 3, "OuterCount assertion failed");
        assertEqual(env.lookup('FinalOuter'), 4, "FinalOuter assertion failed");
        assertEqual(env.lookup('InnerCount'), 3, "InnerCount assertion failed");
        assertEqual(env.lookup('FinalInner'), 2, "FinalInner assertion failed");
        assertEqual(env.lookup('Flag'), 0, "Flag assertion failed");
        assertEqual(env.lookup('FinalK'), 1, "FinalK assertion failed");
    });

    test('DO...LOOP Statement (Pre-test)', () => {
        const code = `
            ' 1. WHILE False -> 0 runs
            RunsPreWhile = 0
            DO WHILE 0
              RunsPreWhile = RunsPreWhile + 1
            LOOP
            
            ' 2. UNTIL True -> 0 runs
            RunsPreUntil = 0
            DO UNTIL -1
              RunsPreUntil = RunsPreUntil + 1
            LOOP
            
            ' 3. WHILE Arbitrary Float (True) -> 1 run
            RunsFloat = 0
            CondF = 42.5
            DO WHILE CondF
              RunsFloat = RunsFloat + 1
              CondF = 0
            LOOP
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('RunsPreWhile'), 0, "RunsPreWhile assertion failed");
        assertEqual(env.lookup('RunsPreUntil'), 0, "RunsPreUntil assertion failed");
        assertEqual(env.lookup('RunsFloat'), 1, "RunsFloat assertion failed");
    });

    test('DO...LOOP Statement (Post-test)', () => {
        const code = `
            RunsPostA = 0
            DO
              RunsPostA = RunsPostA + 1
            LOOP WHILE 0
            
            RunsPostB = 0
            DO
              RunsPostB = RunsPostB + 1
            LOOP UNTIL -1
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('RunsPostA'), 1, "RunsPostA assertion failed");
        assertEqual(env.lookup('RunsPostB'), 1, "RunsPostB assertion failed");
    });

    test('GOSUB...RETURN Statement', () => {
        const code = `
            GlobalVar = 10: StepId = 0
            GOSUB RoutineStart
            StepId = 99
            GOTO EndTest
            
            RoutineStart:
              GlobalVar = GlobalVar * 2
              GOTO RoutineSkip
              GlobalVar = 0 ' MUST NEVER EXECUTE
            RoutineSkip:
              StepId = 1
            RETURN
            
            EndTest:
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('GlobalVar'), 20, "GlobalVar assertion failed");
        assertEqual(env.lookup('StepId'), 99, "StepId assertion failed");
    });

    test('SELECT CASE Statement', () => {
        const code = `
            ' 1. Exact Match, Range (TO), and No Fallthrough
            TestVal = 5: Result = 0: ExecCount = 0
            SELECT CASE TestVal
              CASE 1, 2, 3
                Result = 1: ExecCount = ExecCount + 1
              CASE 4 TO 6
                Result = 2: ExecCount = ExecCount + 1
              CASE 5
                Result = 3: ExecCount = ExecCount + 1 ' MUST NEVER EXECUTE (No fallthrough)
              CASE ELSE
                Result = 4: ExecCount = ExecCount + 1
            END SELECT
            
            ' 2. Relational Matching (CASE IS)
            Score = 85: Grade = 0
            SELECT CASE Score
              CASE IS >= 90
                Grade = 1
              CASE IS >= 80
                Grade = 2
              CASE IS < 50
                Grade = 3
            END SELECT
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('Result'), 2, "Result assertion failed");
        assertEqual(env.lookup('ExecCount'), 1, "ExecCount assertion failed");
        assertEqual(env.lookup('Grade'), 2, "Grade assertion failed");
    });

    test('WHILE...WEND Statement', () => {
        const code = `
            Runs = 0: ValA = 1
            WHILE ValA
              Runs = Runs + 1
              IF Runs = 2 THEN GOTO EscapeWhile
            WEND
            EscapeWhile:
            
            FalseRuns = 0
            WHILE 0
              FalseRuns = 99
            WEND
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('Runs'), 2, "Runs assertion failed");
        assertEqual(env.lookup('FalseRuns'), 0, "FalseRuns assertion failed");
    });

    test('Line Numbers (Archaic Labels)', () => {
        const code = `
            LineVal = 0
            10 LineVal = 10
            GOTO 30
            20 LineVal = 20
            30 FinalLine = LineVal
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('FinalLine'), 10, "FinalLine assertion failed");
    });

    test('Implicit GOTO (IF THEN Line Number)', () => {
        const code = `
            Flag = 1
            IF Flag = 1 THEN 100 ELSE 200
            100 ThenPath = 1
            GOTO 300
            200 ThenPath = 2
            300 Flag = 0
            IF Flag = 1 THEN 400 ELSE 500
            400 ElsePath = 1
            GOTO 600
            500 ElsePath = 2
            600 FinalEnd = 1
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('ThenPath'), 1, "ThenPath assertion failed");
        assertEqual(env.lookup('ElsePath'), 2, "ElsePath assertion failed");
    });
});

registerSuite('Truth Vector: CORE: Memory, Types & Structures', () => {

    test('Default Implicit Typing (SINGLE)', () => {
        const code = `
            DefaultFloat = 3.14
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('DefaultFloat'), 3.14, "DefaultFloat assertion failed");
    });

    test('DEFINT Statement', () => {
        const code = `
            DEFINT A-Z
            ImplicitIntA = 2.5
            ImplicitIntB = 2.6
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('ImplicitIntA'), 2, "ImplicitIntA assertion failed");
        assertEqual(env.lookup('ImplicitIntB'), 3, "ImplicitIntB assertion failed");
    });

    test('DEFSNG Statement', () => {
        const code = `
            DEFINT A-Z
            DEFSNG A-Z
            ImplicitSng = 5.8
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('ImplicitSng'), 5.8, "ImplicitSng assertion failed");
    });

    test('Explicit Type Suffix Override', () => {
        const code = `
            DEFINT A-Z
            OverrideFloat! = 3.14
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('OverrideFloat!'), 3.14, "OverrideFloat! assertion failed");
    });

    test('Memory Aliasing (DIM AS STRING)', () => {
        const code = `
            DIM AliasTest AS STRING
            AliasTest = "NIBBLES"
            Extracted$ = AliasTest$
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('Extracted$'), "NIBBLES", "Extracted$ assertion failed");
    });

    test('Fixed-Length String Padding', () => {
        const code = `
            DIM PadStr AS STRING * 5
            PadStr = "HI"
            PadLen = LEN(PadStr)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('PadStr'), "HI   ", "PadStr assertion failed");
        assertEqual(env.lookup('PadLen'), 5, "PadLen assertion failed");
    });

    test('Fixed-Length String Truncation', () => {
        const code = `
            DIM TruncStr AS STRING * 3
            TruncStr = "123456"
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('TruncStr'), "123", "TruncStr assertion failed");
    });

    test('SWAP Statement', () => {
        const code = `
            ' 1. Scalar Swap
            ValA = 10: ValB = 99
            SWAP ValA, ValB
            
            ' 2. Array Indices Swap
            DIM SwapArr(2)
            SwapArr(1) = 42: SwapArr(2) = 77
            SWAP SwapArr(1), SwapArr(2)
            ArrRes1 = SwapArr(1)
            ArrRes2 = SwapArr(2)
            
            ' 3. Fixed-Length String Swap Integrity
            TYPE SwapType
              F AS STRING * 4
            END TYPE
            DIM ST1 AS SwapType, ST2 AS SwapType
            ST1.F = "A"
            ST2.F = "B"
            SWAP ST1, ST2
            ST1.F = "Z"
            FixedLenAfterSwap = LEN(ST1.F)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('ValA'), 99, "ValA assertion failed");
        assertEqual(env.lookup('ValB'), 10, "ValB assertion failed");
        assertEqual(env.lookup('ArrRes1'), 77, "ArrRes1 assertion failed");
        assertEqual(env.lookup('ArrRes2'), 42, "ArrRes2 assertion failed");
        assertEqual(env.lookup('FixedLenAfterSwap'), 4, "FixedLenAfterSwap assertion failed");
    });

    test('ERASE Statement', () => {
        const code = `
            ' 1. Numeric Array Erase
            DIM NumArr(2)
            NumArr(1) = 42: NumArr(2) = 99
            ERASE NumArr
            CheckNum1 = NumArr(1)
            CheckNum2 = NumArr(2)
            
            ' 2. String Array Erase
            DIM StrArr$(1)
            StrArr$(1) = "Hello World"
            ERASE StrArr$
            CheckStr$ = StrArr$(1)
            
            ' 3. UDT with Fixed-Length String Erase
            TYPE EraseType
              F AS STRING * 4
            END TYPE
            DIM EArr(1) AS EraseType
            EArr(1).F = "TEST"
            ERASE EArr
            EArr(1).F = "X"
            FixedLenAfterErase = LEN(EArr(1).F)
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('CheckNum1'), 0, "CheckNum1 assertion failed");
        assertEqual(env.lookup('CheckNum2'), 0, "CheckNum2 assertion failed");
        assertEqual(env.lookup('CheckStr$'), "", "CheckStr$ assertion failed");
        assertEqual(env.lookup('FixedLenAfterErase'), 4, "FixedLenAfterErase assertion failed");
    });
});

registerSuite('Truth Vector: CORE: Procedures & Functions', () => {

    test('CALL Statement', () => {
        const code = `
            RefVar = 10
            ValVar = 10
            DeepVar = 10
            CALL ScopeTest(RefVar, (ValVar), (((DeepVar))))
            GOTO EndCallTest
            
            SUB ScopeTest (ArgRef, ArgVal, ArgDeep)
              ArgRef = 99
              ArgVal = 99
              ArgDeep = 99
            END SUB
            
            EndCallTest:
        `;
        const env = executeToEnv(code);

        assertEqual(env.lookup('RefVar'), 99, "RefVar assertion failed");
        assertEqual(env.lookup('ValVar'), 10, "ValVar assertion failed");
        assertEqual(env.lookup('DeepVar'), 10, "DeepVar assertion failed");
    });
});
