' ==========================================
' VGA 256 COLORS TEST PATTERN
' Generated by: Gemini 3.1 Pro
' Required Mode: SCREEN 13
' ==========================================
SCREEN 13

FOR i = 0 TO 255
    ' Calculate grid coordinates
    col = i MOD 16
    row = i \ 16
    
    xStart = col * 20
    yStart = row * 12
    
    ' Draw rectangle pixel by pixel
    FOR y = 0 TO 10
        FOR x = 0 TO 18
            PSET (xStart + x, yStart + y), i
        NEXT x
    NEXT y
NEXT i

LOCATE 22, 1
COLOR 15, 0
PRINT "Press any key to exit..."

DO: LOOP UNTIL INKEY$ <> ""