' ==========================================
' MATRIX DIGITAL RAIN
' High-speed text-mode visual effect.
' Generated by: Gemini 3.1 Pro
' Required Mode: SCREEN 0
' ==========================================
SCREEN 0
WIDTH 80, 25
COLOR 2, 0
CLS

RANDOMIZE TIMER
DIM drop(80) AS INTEGER

' Initialize drop positions randomly across the screen
FOR i = 1 TO 80
    drop(i) = INT(RND * 25)
NEXT i

DO
    FOR x = 1 TO 80
        ' Do not update all columns simultaneously to keep it airy
        IF RND > 0.4 THEN
            ' Erase the old position (the end of the tail)
            LOCATE drop(x) + 1, x: PRINT " ";
            
            ' Move the drop down
            drop(x) = drop(x) + 1
            IF drop(x) > 23 THEN drop(x) = 0 ' Limit to 23 to avoid automatic VGA scrolling
            
            ' Draw the head of the drop (Light Green)
            COLOR 10
            LOCATE drop(x) + 1, x
            PRINT CHR$(33 + INT(RND * 222));
            
            ' Draw the tail just above (Dark Green)
            IF drop(x) > 0 THEN
                COLOR 2
                LOCATE drop(x), x
                PRINT CHR$(33 + INT(RND * 222));
            END IF
        END IF
    NEXT x
    
    ' Speed throttling loop to pace execution on modern CPUs
    t! = TIMER
    DO
    LOOP UNTIL TIMER - t! > 0.03
LOOP UNTIL INKEY$ <> ""