' ==========================================
' TRIGONOMETRIC PLASMA
' Real-time VGA palette manipulation (OUT) and math art.
' Generated by: Gemini 3.1 Pro
' Required Mode: SCREEN 13
' ==========================================
SCREEN 13
DEFINT A-Z

DIM r(255), g(255), b(255)

LOCATE 12, 12: PRINT "Generating Geometry..."

' 1. Calculate the static fractal surface ONCE
FOR y = 0 TO 199 STEP 2
    FOR x = 0 TO 319 STEP 2
        ' Complex trigonometric heightmap mapped to 0-255 color indexes
        c = INT(SIN(x / 20) * 20 + COS(y / 20) * 20 + SIN((x + y) / 30) * 15 + 128) MOD 256
        IF c < 0 THEN c = c + 256
        
        PSET (x, y), c
        PSET (x + 1, y), c
        PSET (x, y + 1), c
        PSET (x + 1, y + 1), c
    NEXT x
NEXT y

' 2. Pre-calculate the RGB color waves (6-bit VGA DAC format: 0-63)
FOR i = 0 TO 255
    r(i) = INT(31 + 31 * SIN(i * 3.14 / 64))
    g(i) = INT(31 + 31 * SIN(i * 3.14 / 128))
    b(i) = INT(31 + 31 * SIN(i * 3.14 / 32))
NEXT i

' 3. The true demoscene infinite loop: Palette Cycling
shift = 0
DO
    ' Reset DAC write pointer to index 0
    OUT &H3C8, 0
    
    ' Blast 256 colors * 3 channels = 768 bytes to the hardware port
    FOR i = 0 TO 255
        idx = (i + shift) MOD 256
        OUT &H3C9, r(idx)
        OUT &H3C9, g(idx)
        OUT &H3C9, b(idx)
    NEXT i
    
    shift = (shift + 1) MOD 256
LOOP UNTIL INKEY$ <> ""