// src/parser/qbasic/linter/qbasic_linter.js
import { traverse } from '../../ast_traverser.js';
import { noNativeAssignmentRule } from './rules/no_native_assignment.js';
import { labelIntegrityRule } from './rules/label_integrity.js';
import { orphanFlowRule } from './rules/orphan_flow.js';
import { typeMismatchRule } from './rules/type_mismatch.js';
import { duplicateRoutineRule } from './rules/duplicate_sub.js';

/**
 * Universal Syntax Linter Engine.
 * Delegates actual tree traversal to the agnostic AST Traverser.
 */
export class QBasicLinter {
    constructor() {
        // Register active plugins/rules
        this.rules = [
            noNativeAssignmentRule,
            labelIntegrityRule,
            orphanFlowRule,
            typeMismatchRule,
            duplicateRoutineRule
        ];
        
        // Pre-compile all individual rules into a single high-performance Visitor
        this.visitor = this._buildVisitor();
    }

    /**
     * Merges multiple rule objects into a single visitor dictionary.
     * If multiple rules target the same node type, their functions are chained.
     * @private
     */
    _buildVisitor() {
        const visitor = {};
        for (const rule of this.rules) {
            for (const nodeType in rule) {
                // Ignore lifecycle hooks and private helpers during visitor compilation
                if (nodeType === 'finalize' || nodeType.startsWith('_')) continue;
                
                const existingFn = visitor[nodeType];
                const ruleFn = rule[nodeType];
                
                if (existingFn) {
                    // Chain functions if multiple rules target this node type
                    visitor[nodeType] = (node, state) => {
                        existingFn(node, state);
                        ruleFn(node, state);
                    };
                } else {
                    visitor[nodeType] = ruleFn;
                }
            }
        }
        return visitor;
    }

    /**
     * Performs a static analysis pass (Dry Run) on the AST.
     * @param {Object|Array} ast - The syntax tree generated by the parser.
     * @returns {Array<string>} A list of syntax errors found.
     */
    lint(ast) {
        // Initialize the shared state for the current linting session
        const state = {
            errors: [],
            definedLabels: new Set(),
            usedLabels: [],
            definedRoutines: new Set(),
            loopStack: [],
            routineStack: []
        };

        // 1. Let the universal Traverser do the heavy lifting
        traverse(ast, this.visitor, state);

        // 2. Trigger post-traversal hooks (e.g., verifying if a GOTO target was actually defined)
        for (const rule of this.rules) {
            if (typeof rule.finalize === 'function') {
                rule.finalize(state);
            }
        }

        return state.errors;
    }
}