// tools/truth_compiler/qbasic_target.js
import fs from 'fs';
import path from 'path';

/**
 * Formats JSON values into valid QBasic or JavaScript literals.
 */
function formatValue(val, type) {
    if (type === 'string') return `"${val}"`;
    return val; // Numbers and booleans remain unquoted
}

/**
 * Builds the QBasic visual ROM for DOSBox testing.
 */
export function buildQBasic(suites, rootDir) {
    const OUT_BAS = path.resolve(rootDir, '../examples/compat.bas');

    const lines = [
        "' ==============================================================================",
        "' SYSCLONE COMPATIBILITY HARNESS (Auto-Generated)",
        "' Runs silently. Only prints failures and the final score.",
        "' ==============================================================================",
        "TotalTests% = 0: PassedTests% = 0: FailedTests% = 0",
        "PRINT \"Running Sysclone Truth Vectors...\"",
        "PRINT \"---------------------------------\""
    ];

    suites.forEach(suite => {
        lines.push("", `' --- SUITE: ${suite.suite} ---`);
        
        suite.vectors.forEach(vec => {
            if (!vec.quirks_and_tests) return;

            lines.push("", `' Vector: ${vec.name}`, ...vec.quirks_and_tests.setup);
            
            vec.quirks_and_tests.assertions.forEach(assert => {
                const expected = formatValue(assert.val, assert.type);
                const logic = [
                    `TotalTests% = TotalTests% + 1`,
                    `IF ${assert.var} = ${expected} THEN`,
                    `  PassedTests% = PassedTests% + 1`,
                    `ELSE`,
                    `  FailedTests% = FailedTests% + 1`
                ];
                
                lines.push(
                    ...logic, 
                    `  PRINT "FAIL: [${vec.name}] ${assert.var} expected "; ${expected}; " but got "; ${assert.var}`, 
                    `END IF`
                );
            });
        });
    });

    lines.push(
        "",
        "' --- FINAL REPORT ---",
        "PRINT \"---------------------------------\"",
        "IF FailedTests% = 0 THEN COLOR 10 ELSE COLOR 12",
        "PRINT \"PASSED: \"; PassedTests%; \" / \"; TotalTests%",
        "COLOR 7"
    );

    fs.writeFileSync(OUT_BAS, lines.join('\n'), 'utf8');
}

/**
 * Builds the JavaScript Unit Tests for the Sysclone Evaluator.
 */
export function buildJSTests(suites, rootDir) {
    const OUT_JS = path.resolve(rootDir, '../src/runtime/qbasic/compatibility.test.js');
    const relativeJSPath = path.relative(path.resolve(rootDir, '..'), OUT_JS).replace(/\\/g, '/');

    const lines = [
        `// ${relativeJSPath}`,
        "// ==============================================================================",
        "// AUTO-GENERATED BY tools/build_truth.js - DO NOT EDIT MANUALLY",
        "// ==============================================================================",
        "import { Evaluator } from '../evaluator.js';",
        "import { block } from '../../parser/qbasic/controlFlow.js';",
        "import { test, assertEqual, registerSuite } from '../../test_runner.js';",
        "",
        "function executeToEnv(sourceCode) {",
        "    const evaluator = new Evaluator();",
        "    const ast = block.run(sourceCode).result;",
        "    const process = evaluator.evaluate(ast);",
        "    let state = process.next();",
        "    while (!state.done) state = process.next();",
        "    return evaluator.env;",
        "}"
    ];

    suites.forEach(suite => {
        lines.push("", `registerSuite('Truth Vector: ${suite.suite}', () => {`);
        
        suite.vectors.forEach(vec => {
            if (!vec.quirks_and_tests) return;
            
            const safeName = vec.name.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/`/g, '\\`');
            
            lines.push(
                "", 
                `    test('${safeName}', () => {`, 
                "        const code = `"
            );
            
            vec.quirks_and_tests.setup.forEach(line => {
                const safeLine = line.replace(/\\/g, '\\\\').replace(/`/g, '\\`');
                lines.push(`            ${safeLine}`);
            });
            
            lines.push(
                "        `;", 
                "        const env = executeToEnv(code);", 
                ""
            );
            
            vec.quirks_and_tests.assertions.forEach(assert => {
                const expected = formatValue(assert.val, assert.type);
                lines.push(`        assertEqual(env.lookup('${assert.var}'), ${expected}, "${assert.var} assertion failed");`);
            });
            
            lines.push("    });");
        });
        
        lines.push("});");
    });

    const dir = path.dirname(OUT_JS);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

    fs.writeFileSync(OUT_JS, lines.join('\n') + '\n', 'utf8');
}