// tools/build_truth.js
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const VECTORS_DIR = path.resolve(__dirname, '../tests/truth_vectors');
const OUT_BAS = path.resolve(__dirname, '../examples/compat.bas');
const OUT_JS = path.resolve(__dirname, '../src/runtime/compatibility.test.js');
const OUT_MD = path.resolve(__dirname, '../docs/QBASIC_REFERENCE.MD');

function formatValue(val, type) {
    if (type === 'string') return `"${val}"`;
    return val; // Numbers and booleans
}

function buildQBasicRom(suites) {
    let basCode = `
' ==============================================================================
' SYSCLONE COMPATIBILITY HARNESS (Auto-Generated)
' Runs silently. Only prints failures and the final score.
' ==============================================================================
DEFINT A-Z
TotalTests = 0
PassedTests = 0
FailedTests = 0

PRINT "Running Sysclone Truth Vectors..."
PRINT "---------------------------------"
`;

    suites.forEach(suite => {
        basCode += `\n' --- SUITE: ${suite.suite} ---\n`;
        suite.vectors.forEach(vec => {
            if (!vec.quirks_and_tests) return; // Skip if no tests defined

            basCode += `\n' Vector: ${vec.name}\n`;
            vec.quirks_and_tests.setup.forEach(line => { basCode += `${line}\n`; });
            
            vec.quirks_and_tests.assertions.forEach(assert => {
                const expected = formatValue(assert.val, assert.type);
                basCode += `TotalTests = TotalTests + 1\n`;
                basCode += `IF ${assert.var} = ${expected} THEN\n`;
                basCode += `  PassedTests = PassedTests + 1\n`;
                basCode += `ELSE\n`;
                basCode += `  FailedTests = FailedTests + 1\n`;
                basCode += `  PRINT "FAIL: [${vec.name}] ${assert.var} expected "; ${expected}; " but got "; ${assert.var}\n`;
                basCode += `END IF\n`;
            });
        });
    });

    basCode += `
' --- FINAL REPORT ---
PRINT "---------------------------------"
IF FailedTests = 0 THEN COLOR 10 ELSE COLOR 12
PRINT "PASSED: "; PassedTests; " / "; TotalTests
COLOR 7
`;
    fs.writeFileSync(OUT_BAS, basCode.trim() + '\n', 'utf8');
}

function buildJSTests(suites) {
    let jsCode = `// src/runtime/compatibility.test.js
// ==============================================================================
// AUTO-GENERATED BY tools/build_truth.js - DO NOT EDIT MANUALLY
// ==============================================================================
import { Evaluator } from './evaluator.js';
import { block } from '../parser/qbasic/controlFlow.js';
import { test, assertEqual, registerSuite } from '../test_runner.js';

function executeToEnv(sourceCode) {
    const evaluator = new Evaluator(); 
    const ast = block.run(sourceCode).result;
    const process = evaluator.evaluate(ast);
    let state = process.next();
    while (!state.done) state = process.next();
    return evaluator.env; 
}
`;

    suites.forEach(suite => {
        jsCode += `\nregisterSuite('Truth Vector: ${suite.suite}', () => {\n`;
        suite.vectors.forEach(vec => {
            if (!vec.quirks_and_tests) return;

            // 🛡️ THE FIX: Safely escape the test name for JS injection
            const safeName = vec.name.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/`/g, '\\`');
            jsCode += `\n    test('${safeName}', () => {\n`;
            jsCode += `        const code = \`\n`;
            
            vec.quirks_and_tests.setup.forEach(line => { 
                // 🛡️ THE FIX: Escape backslashes (\) and backticks (`) for JS template literals
                const safeLine = line.replace(/\\/g, '\\\\').replace(/`/g, '\\`');
                jsCode += `            ${safeLine}\n`; 
            });
            
            jsCode += `        \`;\n`;
            jsCode += `        const env = executeToEnv(code);\n\n`;
            
            vec.quirks_and_tests.assertions.forEach(assert => {
                const expected = formatValue(assert.val, assert.type);
                jsCode += `        assertEqual(env.lookup('${assert.var}'), ${expected}, "${assert.var} assertion failed");\n`;
            });
            jsCode += `    });\n`;
        });
        jsCode += `});\n`;
    });

    fs.writeFileSync(OUT_JS, jsCode.trim() + '\n', 'utf8');
}

function buildMarkdownDoc(suites) {
    let mdCode = `# Sysclone QBasic Compatibility Reference\n\n`;
    mdCode += `> **Auto-generated** from Truth Vectors. This document serves as the absolute specification for MS-DOS QBasic behavior.\n\n`;

    // --- 1. Global Alphabetical Index (100% PURE MARKDOWN) ---
    mdCode += `## 🔠 Alphabetical Index\n\n`;
    const allVectors = [];
    suites.forEach(suite => {
        suite.vectors.forEach(vec => {
            allVectors.push({ name: vec.name, anchor: vec.name.toLowerCase().replace(/[^a-z0-9]+/g, '-') });
        });
    });
    
    // Sort alphabetically
    allVectors.sort((a, b) => a.name.localeCompare(b.name));
    
    // Generate a compact inline list separated by bullets
    const indexLinks = allVectors.map(v => `[${v.name}](#${v.anchor})`);
    mdCode += indexLinks.join(' • ') + `\n\n---\n\n`;

    // --- 2. Categorized Table of Contents ---
    mdCode += `## 📚 Thematic Contents\n\n`;
    suites.forEach(suite => {
        mdCode += `- **${suite.suite}**\n`;
        suite.vectors.forEach(vec => {
            const anchor = vec.name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
            mdCode += `  - [${vec.name}](#${anchor})\n`;
        });
    });
    mdCode += `\n---\n\n`;

    // --- 3. Body Content (Grouped by Suite) ---
    suites.forEach(suite => {
        mdCode += `## ${suite.suite}\n\n`;
        
        suite.vectors.forEach(vec => {
            mdCode += `### ${vec.name}\n\n`;
            
            if (vec.syntax) mdCode += `**Syntax:** \`${vec.syntax}\`\n\n`;
            if (vec.description) mdCode += `${vec.description}\n\n`;
            
            if (vec.example) {
                mdCode += `**Example:**\n\`\`\`basic\n`;
                vec.example.code.forEach(line => { mdCode += `${line}\n`; });
                mdCode += `\`\`\`\n`;
                mdCode += `**Output:**\n\`\`\`text\n${vec.example.output}\n\`\`\`\n\n`;
            }

            if (vec.quirks_and_tests) {
                mdCode += `#### 🔬 Hardware Quirks & Edge Cases\n\n`;
                if (vec.quirks_and_tests.description) {
                    mdCode += `${vec.quirks_and_tests.description}\n\n`;
                }
                
                mdCode += `\`\`\`basic\n`;
                vec.quirks_and_tests.setup.forEach(line => { mdCode += `${line}\n`; });
                mdCode += `\`\`\`\n`;
                
                // --- THE NEW MEMORY STATE DISPLAY ---
                mdCode += `**Memory State (End of Execution):**\n`;
                mdCode += `\`\`\`text\n`;
                
                // Dynamic alignment for perfect aesthetics
                const maxVarLen = Math.max(...vec.quirks_and_tests.assertions.map(a => a.var.length));
                
                vec.quirks_and_tests.assertions.forEach(assert => {
                    const expected = formatValue(assert.val, assert.type);
                    const paddedVar = assert.var.padEnd(maxVarLen, ' ');
                    // 🛡️ THE FIX: Cast to String before calling padEnd
                    mdCode += `${paddedVar} = ${String(expected).padEnd(12, ' ')} (${assert.type})\n`;
                });
                mdCode += `\`\`\`\n`;
            }
            mdCode += `\n---\n\n`;
        });
    });

    fs.writeFileSync(OUT_MD, mdCode.trim() + '\n', 'utf8');
}

try {
    if (!fs.existsSync(VECTORS_DIR)) fs.mkdirSync(VECTORS_DIR, { recursive: true });
    
    const files = fs.readdirSync(VECTORS_DIR).filter(f => f.endsWith('.json'));
    const suites = files.map(f => JSON.parse(fs.readFileSync(path.join(VECTORS_DIR, f), 'utf8')));
    
    if (suites.length > 0) {
        buildQBasicRom(suites);
        buildJSTests(suites);
        buildMarkdownDoc(suites);
        console.log(`✅ Truth Vectors built successfully!`);
        console.log(`   - Generated: examples/compat.bas`);
        console.log(`   - Generated: src/runtime/compatibility.test.js`);
        console.log(`   - Generated: docs/QBASIC_REFERENCE.MD`);
    } else {
        console.log(`⚠️ No JSON truth vectors found in ${VECTORS_DIR}`);
    }
} catch (error) {
    console.error(`❌ Build Error: ${error.message}`);
    process.exit(1);
}