// tools/build_truth.js
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const VECTORS_DIR = path.resolve(__dirname, '../tests/truth_vectors');
const OUT_BAS = path.resolve(__dirname, '../examples/compat.bas');
const OUT_JS = path.resolve(__dirname, '../src/runtime/compatibility.test.js');
const OUT_MD = path.resolve(__dirname, '../docs/QBASIC_REFERENCE.MD');

function formatValue(val, type) {
    if (type === 'string') return `"${val}"`;
    return val; // Numbers and booleans
}

function buildQBasicRom(suites) {
    const lines = [
        "' ==============================================================================",
        "' SYSCLONE COMPATIBILITY HARNESS (Auto-Generated)",
        "' Runs silently. Only prints failures and the final score.",
        "' ==============================================================================",
        "TotalTests% = 0",
        "PassedTests% = 0",
        "FailedTests% = 0",
        "",
        "PRINT \"Running Sysclone Truth Vectors...\"",
        "PRINT \"---------------------------------\""
    ];

    suites.forEach(suite => {
        lines.push(
            "",
            `' --- SUITE: ${suite.suite} ---`
        );

        suite.vectors.forEach(vec => {
            if (!vec.quirks_and_tests) return; // Skip if no tests defined

            lines.push(
                "",
                `' Vector: ${vec.name}`
            );
            lines.push(...vec.quirks_and_tests.setup);
            
            vec.quirks_and_tests.assertions.forEach(assert => {
                const expected = formatValue(assert.val, assert.type);
                lines.push(
                    `TotalTests% = TotalTests% + 1`,
                    `IF ${assert.var} = ${expected} THEN`,
                    `  PassedTests% = PassedTests% + 1`,
                    `ELSE`,
                    `  FailedTests% = FailedTests% + 1`,
                    `  PRINT "FAIL: [${vec.name}] ${assert.var} expected "; ${expected}; " but got "; ${assert.var}`,
                    `END IF`
                );
            });
        });
    });

    lines.push(
        "",
        "' --- FINAL REPORT ---",
        "PRINT \"---------------------------------\"",
        "IF FailedTests% = 0 THEN COLOR 10 ELSE COLOR 12",
        "PRINT \"PASSED: \"; PassedTests%; \" / \"; TotalTests%",
        "COLOR 7",
        ""
    );

    fs.writeFileSync(OUT_BAS, lines.join('\n'), 'utf8');
}

function buildJSTests(suites) {
    const lines = [
        "// src/runtime/compatibility.test.js",
        "// ==============================================================================",
        "// AUTO-GENERATED BY tools/build_truth.js - DO NOT EDIT MANUALLY",
        "// ==============================================================================",
        "import { Evaluator } from './evaluator.js';",
        "import { block } from '../parser/qbasic/controlFlow.js';",
        "import { test, assertEqual, registerSuite } from '../test_runner.js';",
        "",
        "function executeToEnv(sourceCode) {",
        "    const evaluator = new Evaluator();",
        "    const ast = block.run(sourceCode).result;",
        "    const process = evaluator.evaluate(ast);",
        "    let state = process.next();",
        "    while (!state.done) state = process.next();",
        "    return evaluator.env;",
        "}"
    ];

    suites.forEach(suite => {
        lines.push("", `registerSuite('Truth Vector: ${suite.suite}', () => {`);
        
        suite.vectors.forEach(vec => {
            if (!vec.quirks_and_tests) return;

            // Safely escape the test name for JS injection
            const safeName = vec.name.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/`/g, '\\`');
            
            lines.push(
                "",
                `    test('${safeName}', () => {`,
                "        const code = `"
            );
            
            vec.quirks_and_tests.setup.forEach(line => { 
                // Escape backslashes (\) and backticks (`) for JS template literals
                const safeLine = line.replace(/\\/g, '\\\\').replace(/`/g, '\\`');
                lines.push(`            ${safeLine}`); 
            });
            
            lines.push(
                "        `;",
                "        const env = executeToEnv(code);",
                ""
            );
            
            vec.quirks_and_tests.assertions.forEach(assert => {
                const expected = formatValue(assert.val, assert.type);
                lines.push(`        assertEqual(env.lookup('${assert.var}'), ${expected}, "${assert.var} assertion failed");`);
            });
            
            lines.push("    });");
        });
        
        lines.push("});");
    });

    // Assemble cleanly with explicit newlines
    fs.writeFileSync(OUT_JS, lines.join('\n') + '\n', 'utf8');
}

function buildMarkdownDoc(suites) {
    const lines = [
        "# Sysclone QBasic Compatibility Reference",
        "",
        "> **Auto-generated** from Truth Vectors. This document serves as the absolute specification for MS-DOS QBasic behavior.",
        "",
        "## 🔠 Alphabetical Index",
        ""
    ];

    // --- 1. Global Alphabetical Index (100% PURE MARKDOWN) ---
    const allVectors = [];
    suites.forEach(suite => {
        suite.vectors.forEach(vec => {
            allVectors.push({ name: vec.name, anchor: vec.name.toLowerCase().replace(/[^a-z0-9]+/g, '-') });
        });
    });
    
    // Sort alphabetically
    allVectors.sort((a, b) => a.name.localeCompare(b.name));
    
    // Generate a compact inline list separated by bullets
    const indexLinks = allVectors.map(v => `[${v.name}](#${v.anchor})`);
    lines.push(
        indexLinks.join(' • '),
        "",
        "---",
        "",
        "## 📚 Thematic Contents",
        ""
    );

    // --- 2. Categorized Table of Contents ---
    suites.forEach(suite => {
        lines.push(`- **${suite.suite}**`);
        suite.vectors.forEach(vec => {
            const anchor = vec.name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
            lines.push(`  - [${vec.name}](#${anchor})`);
        });
    });
    lines.push("", "---", "");

    // --- 3. Body Content (Grouped by Suite) ---
    suites.forEach(suite => {
        lines.push(`## ${suite.suite}`, "");
        
        suite.vectors.forEach(vec => {
            lines.push(`### ${vec.name}`, "");
            
            if (vec.syntax) lines.push(`**Syntax:** \`${vec.syntax}\``, "");
            if (vec.description) lines.push(vec.description, "");
            
            if (vec.example) {
                lines.push(
                    "**Example:**",
                    "```basic",
                    ...vec.example.code,
                    "```",
                    "**Output:**",
                    "```text",
                    vec.example.output,
                    "```",
                    ""
                );
            }

            if (vec.quirks_and_tests) {
                lines.push("#### 🔬 Hardware Quirks & Edge Cases", "");
                
                if (vec.quirks_and_tests.description) {
                    lines.push(vec.quirks_and_tests.description, "");
                }
                
                lines.push(
                    "```basic",
                    ...vec.quirks_and_tests.setup,
                    "```",
                    "**Memory State (End of Execution):**",
                    "```text"
                );
                
                // Dynamic alignment for perfect aesthetics
                const maxVarLen = Math.max(...vec.quirks_and_tests.assertions.map(a => a.var.length));
                
                vec.quirks_and_tests.assertions.forEach(assert => {
                    const expected = formatValue(assert.val, assert.type);
                    const paddedVar = assert.var.padEnd(maxVarLen, ' ');
                    // Cast to String before calling padEnd
                    lines.push(`${paddedVar} = ${String(expected).padEnd(12, ' ')} (${assert.type})`);
                });
                
                lines.push("```", "");
            }
            lines.push("---", "");
        });
    });

    // Write file, trim trailing newlines and guarantee a clean EOF
    fs.writeFileSync(OUT_MD, lines.join('\n').trim() + '\n', 'utf8');
}

try {
    if (!fs.existsSync(VECTORS_DIR)) fs.mkdirSync(VECTORS_DIR, { recursive: true });
    
    const files = fs.readdirSync(VECTORS_DIR).filter(f => f.endsWith('.json'));
    const suites = files.map(f => JSON.parse(fs.readFileSync(path.join(VECTORS_DIR, f), 'utf8')));
    
    if (suites.length > 0) {
        buildQBasicRom(suites);
        buildJSTests(suites);
        buildMarkdownDoc(suites);
        console.log(`✅ Truth Vectors built successfully!`);
        console.log(`   - Generated: examples/compat.bas`);
        console.log(`   - Generated: src/runtime/compatibility.test.js`);
        console.log(`   - Generated: docs/QBASIC_REFERENCE.MD`);
    } else {
        console.log(`⚠️ No JSON truth vectors found in ${VECTORS_DIR}`);
    }
} catch (error) {
    console.error(`❌ Build Error: ${error.message}`);
    process.exit(1);
}